name: Deploy React App to Droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: 167.99.222.76
          username: rene
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/renem.me"
