name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Clean old files on server
        uses: appleboy/ssh-action@master
        with:
          host: 167.99.222.76
          username: rene
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            rm -rf /var/www/renem.me/*

      - name: Upload build to server
        uses: appleboy/scp-action@master
        with:
          host: 167.99.222.76
          username: rene
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/renem.me/"
